set nocompatible           " Explicitly switch to vim mode, not vi-compatible

filetype plugin indent on  " Load plugins according to detected filetype.
syntax on                  " Enable syntax highlighting.

set autoindent             " Indent according to previous line, if no plugin
set expandtab              " Use spaces instead of tabs.
set tabstop     =8
set softtabstop =8         " Tab key indents by 8 spaces.
set shiftwidth  =8         " >> indents by 8 spaces.
set shiftround             " >> indents to next multiple of 'shiftwidth'.

set backspace   =indent,eol,start  " Make backspace work as you would expect.
set hidden                 " Switch between buffers without having to save first.
"set laststatus  =2         " Always show statusline.
set ruler
set display     =lastline  " Show as much as possible of the last line.

set showmode               " Show current mode in command-line.
set showcmd                " Show already typed keys when more are expected.

set incsearch              " Highlight while searching with / or ?.
set hlsearch               " Keep matches highlighted.

set ttyfast                " Faster redrawing.
set lazyredraw             " Only redraw when necessary.

set splitbelow             " Open new windows below the current window.
set splitright             " Open new windows right of the current window.

" set cursorline             " Find the current line quickly.
set wrapscan               " Searches wrap around end-of-file.
set report      =0         " Always report changed lines.
set synmaxcol   =200       " Only highlight the first 200 columns.
set nowrap                 " Disable line wrapping

set ignorecase smartcase   " Search is only case-sensitive if capitals are used

set list                   " Show non-printable characters.
if has('multi_byte') && &encoding ==# 'utf-8'
        let &listchars = 'tab:▸ ,extends:❯,precedes:❮,nbsp:±'
else
        let &listchars = 'tab:> ,extends:>,precedes:<,nbsp:.'
endif

" Cursor shape changes in terminals
" https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
if &term !~# 'linux$'
        let &t_EI = "\e[1 q" " Normal = blinking box
        let &t_SI = "\e[5 q" " Insert = blinking bar
        let &t_SR = "\e[3 q" " Replace = blinking underline
endif

" Fixing cursor shape on enter
augroup ResetCursorShape
        autocmd!
        autocmd VimEnter * normal! :startinsert :stopinsert
augroup END

" The fish shell is not very compatible to other shells and unexpectedly
" breaks things that use 'shell'.
if &shell =~# 'fish$'
        set shell=/bin/bash
endif

" GUI Options
if has("gui_running")
        set guioptions-=T " Disable toolbar
        set guioptions-=m " Disable menubar
        set guioptions-=r " Disable right scrollbar
        set guioptions-=R " Disable right scrollbar
        set guioptions-=l " Disable left scrollbar
        set guioptions-=L " Disable left scrollbar
        set guioptions-=b " Disable bottom scrollbar

        set columns=80 lines=24

        " Font setup
        if has("gui_win32")
                " Windows
                set guifont=Source_Code_Pro:h15
        elseif has("gui_mac")
                " Mac
                set guifont=SourceCodePro-Regular:h15
        else
                set guifont=Source\ Code\ Pro\ 15
        endif

endif

" Custom file type options
autocmd FileType html       setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType javascript setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType java       setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType xml        setlocal ts=2 sts=2 sw=2 expandtab

" Selenized (better Solarized)
silent! colorscheme selenized_bw

" Anti-flashbang protocol 2.0
if empty($COLORFGBG) 
        \ && exists("*strftime") && (strftime("%H")>=21 || strftime("%H")<=9)
        set background=dark
endif
        

" Old crap I need to sort through and selectively bring back in probably
" XDG Base Dir is officially coming in a newer version. Need to find that and
" craft my vimrc to match, so the update will be seamless with defaults

" Conform to XDG Base Dir spec
"set runtimepath^=$XDG_CONFIG_HOME/vim
"set runtimepath+=$XDG_DATA_HOME/vim
"set runtimepath+=$XDG_CONFIG_HOME/vim/after

"set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
"set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

"let g:netrw_home = $XDG_DATA_HOME."/vim"
" call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
"set viewdir=$XDG_DATA_HOME/vim/view "| call mkdir(&viewdir, 'p')

"set backupdir=$XDG_CACHE_HOME/vim/backup "| call mkdir(&backupdir, 'p')
"set directory=$XDG_CACHE_HOME/vim/swap   "| call mkdir(&directory, 'p')
"set undodir=$XDG_CACHE_HOME/vim/undo     "| call mkdir(&undodir,   'p')

"if !has('nvim') | set viminfofile=$XDG_CACHE_HOME/vim/viminfo | endif

" Put all temporary files under the same directory.
" https://github.com/mhinz/vim-galore#temporary-files
" Modified to support the XDG Base Dir spec conform
"set backup
"set backupdir   =$HOME/.vim/files/backup/
"set backupext   =-vimbackup
"set backupskip  =
"set directory   =$HOME/.vim/files/swap//
"set updatecount =100
"set undofile
"set undodir     =$HOME/.vim/files/undo/
"set viminfo     ='100,n$HOME/.vim/files/info/viminfo

"set number  " Line numbers
