set nocompatible           " Explicitly switch to vim mode, not vi-compatible

filetype plugin indent on  " Load plugins according to detected filetype.
syntax on                  " Enable syntax highlighting.

set autoindent             " Indent according to previous line, if no plugin
set expandtab              " Use spaces instead of tabs.
set tabstop     =8
set softtabstop =8         " Tab key indents by 8 spaces.
set shiftwidth  =8         " >> indents by 8 spaces.
set shiftround             " >> indents to next multiple of 'shiftwidth'.

set backspace   =indent,eol,start  " Make backspace work as you would expect.
set hidden                 " Switch between buffers without having to save first.
"set laststatus  =2         " Always show statusline.
set ruler
set display     =lastline  " Show as much as possible of the last line.

set showmode               " Show current mode in command-line.
set showcmd                " Show already typed keys when more are expected.

set incsearch              " Highlight while searching with / or ?.
set hlsearch               " Keep matches highlighted.

set ttyfast                " Faster redrawing.
set lazyredraw             " Only redraw when necessary.

set splitbelow             " Open new windows below the current window.
set splitright             " Open new windows right of the current window.

" set cursorline             " Find the current line quickly.
set wrapscan               " Searches wrap around end-of-file.
set report      =0         " Always report changed lines.
set synmaxcol   =200       " Only highlight the first 200 columns.
set nowrap                 " Disable line wrapping

set ignorecase smartcase   " Search is only case-sensitive if capitals are used

set list                   " Show non-printable characters.
if has('multi_byte') && &encoding ==# 'utf-8'
        let &listchars = 'tab:▸ ,extends:❯,precedes:❮,nbsp:±'
else
        let &listchars = 'tab:> ,extends:>,precedes:<,nbsp:.'
endif

" Cursor shape changes in terminals
" https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
if &term !~# 'linux$'
        let &t_EI = "\e[1 q" " Normal = blinking box
        let &t_SI = "\e[5 q" " Insert = blinking bar
        if exists('+t_SR')
                let &t_SR = "\e[3 q" " Replace = blinking underline
        endif
endif

" Fixing cursor shape on enter
augroup ResetCursorShape
        autocmd!
        autocmd VimEnter * normal! :startinsert :stopinsert
augroup END

" The fish shell is not very compatible to other shells and unexpectedly
" breaks things that use 'shell'.
if &shell =~# 'fish$'
        set shell=/bin/bash
endif

" GUI Options
if has("gui_running")
        set guioptions-=T " Disable toolbar
        set guioptions-=m " Disable menubar
        set guioptions-=r " Disable right scrollbar
        set guioptions-=R " Disable right scrollbar
        set guioptions-=l " Disable left scrollbar
        set guioptions-=L " Disable left scrollbar
        set guioptions-=b " Disable bottom scrollbar

        set columns=80 lines=24

        " Font setup
        if has("gui_win32")
                " Windows
                set guifont=Source_Code_Pro:h15
        elseif has("gui_mac") || has("gui_macvim")
                " Mac
                set guifont=SourceCodePro-Regular:h15
        else
                set guifont=Source\ Code\ Pro\ 15
        endif

endif

set textwidth=80           " Auto-format to 80 columns

" Custom file type options
autocmd FileType html       setlocal ts=2 sts=2 sw=2 expandtab textwidth=80
autocmd FileType javascript setlocal ts=2 sts=2 sw=2 expandtab textwidth=80
autocmd FileType typescript setlocal ts=2 sts=2 sw=2 expandtab textwidth=80
autocmd FileType java       setlocal ts=2 sts=2 sw=2 expandtab textwidth=80
autocmd FileType xml        setlocal ts=2 sts=2 sw=2 expandtab textwidth=80
autocmd FileType python     setlocal ts=2 sts=2 sw=2 expandtab textwidth=79
autocmd FileType cpp        setlocal ts=4 sts=4 sw=4 expandtab textwidth=80
autocmd FileType c          setlocal ts=8 sts=8 sw=8 expandtab textwidth=80
autocmd FileType rust       setlocal ts=4 sts=4 sw=4 expandtab textwidth=100
autocmd FileType text       setlocal ts=8 sts=8 sw=8 expandtab textwidth=72
autocmd FileType ps1        setlocal ts=4 sts=4 sw=4 expandtab textwidth=115
autocmd FileType tmux       setlocal ts=8 sts=8 sw=8 expandtab textwidth=0

set cc=+1                  " Highlight the column after textwidth

" Selenized (better Solarized)
silent! colorscheme selenized_bw

" Anti-flashbang protocol 2.0
if empty($COLORFGBG)
        if exists("*strftime")
                if (strftime("%H")>=17 || strftime("%H")<8)
                        set background=dark
                endif
        else
                set background=dark
        endif
endif

" Conform to XDG Base Dir spec
let s:xdg_defaults = {
        \ 'XDG_DATA_HOME':   $HOME . '/.local/share',
        \ 'XDG_DATA_DIRS':   '/usr/local/share:/usr/share',
        \ 'XDG_CONFIG_HOME': $HOME . '/.config',
        \ 'XDG_CONFIG_DIRS': '/etc/xdg',
        \ 'XDG_STATE_HOME':  $HOME . '/.local/state',
        \ 'XDG_CACHE_HOME':  $HOME . '/.cache',
\ }
for key in keys(s:xdg_defaults)
        if ! exists('$' . key)
                execute 'let $' . key . ' = s:xdg_defaults[key]'
        endif
endfor

set backupdir=$XDG_CACHE_HOME/vim/backup
set directory=$XDG_CACHE_HOME/vim/swap
set undodir=$XDG_CACHE_HOME/vim/undo
set viewdir=$XDG_DATA_HOME/vim/view
if exists('*mkdir')
        for dir in [&backupdir, &directory, &undodir, &viewdir,]
                if ! isdirectory(dir)
                        call mkdir(dir, 'p')
                endif
        endfor
endif

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

if exists('+packpath')
        set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
        set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
endif

let g:netrw_home = $XDG_DATA_HOME . "/vim"

if ! has('nvim')
        if exists('+viminfofile')
                set viminfofile=$XDG_CACHE_HOME/vim/viminfo
        else
                set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
        endif
endif
