# Automatic rename to show titles set by commands
set-option -sg automatic-rename-format "#{?pane_in_mode,[tmux],#{pane_title}}#{?pane_dead,[dead],}"

# Add COLORFGBG to variables to update on new / attached sessions
set-option -sga update-environment COLORFGBG

# Arrows + color for active pane
set-option -sg pane-border-indicators both

# Set term emulator window titles
set-option -sg set-titles on
set-option -sg set-titles-string "#T"

# Start non-login shells
set-option -sg default-command "${SHELL}"

# Dynamic statusbar for ssh sessions
set-option -sg status-right "#h#{?!#{SSH_CONNECTION}, %R %F}"
# Simplified: short hostname, time, date
#set-option -sg status-right "#h %R %F"
# Status date to YYYY-MM-DD instead of DD-mmm-YY
#set-option -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}#{?#{>:#{w:pane_title},22},#{=/19/...:pane_title},#{pane_title}} %R %F"
# The window variables seem to be a newer thing?
#set-option -g status-right "#{?#{>:#{w:pane_title},22},#{=/19/...:pane_title},#{pane_title}} %R %F"

# Dynamic color for ssh sessions
%if "!#{SSH_CONNECTION}"
        set-option -sg status-style "fg=black,bg=cyan"
        set-option -sg pane-active-border-style "fg=black,bg=cyan,reverse"
%else
        set-option -sg status-style "fg=black,bg=green"
        set-option -sg pane-active-border-style "fg=black,bg=green,reverse"
%endif

## Vim-friendly bindings
## Biggest change is changing prefix from Ctrl-b to Ctrl-a
# Prefix is Ctrl-a
set-option -sg prefix C-a
bind C-a send-prefix
unbind C-b

# Not sure what difference this makes
set-option -sg escape-time 1

# Mouse works as expected
set-option -sg mouse on

set-option -swg monitor-activity on
set-option -sg visual-activity on

set-option -sg mode-keys vi
set-option -sg history-limit 10000

# y and p as in vim
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi 'Space' send -X halfpage-down
bind-key -T copy-mode-vi 'Bspace' send -X halfpage-up

# extra commands for interacting with the ICCCM clipboard
bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

# easy-to-remember split pane commands
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# moving between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# moving between windows with vim movement keys
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# resize panes with vim movement keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

